name: Run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest, windows

    steps:
    - uses: actions/checkout@v3
      # TODO: Add more?
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install libcst, ruff.
      run: |
        python -m pip install --upgrade pip
        pip install libcst ruff
    - name: Lint with Ruff
      run: |
        python -m ruff .
    - name: Test with pytest
      run: |
        pytest